services:
  budgets-db:
    image: bitnami/postgresql:latest
    environment:
      POSTGRESQL_DATABASE: budgets_db
      POSTGRESQL_PASSWORD: secretpass
      POSTGRESQL_USERNAME: rxman
    ports:
      - '5430:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - budget_network
    restart: always

volumes:
  postgres_data:
networks:
  budget_network:
    driver: bridge
